FROM pgvector/pgvector:pg16 AS pgvector

FROM zhparser/zhparser:bookworm-16

COPY --from=pgvector /usr/lib/postgresql/16/lib/vector.so /usr/lib/postgresql/16/lib/vector.so
COPY --from=pgvector /usr/share/postgresql/16/extension/vector* /usr/share/postgresql/16/extension/
